### ISSUE TITLE
Top bar “System Menu” color of active vs inactive buttons hard to tell apart

### ISSUE THREAD

**Issue by 53R3n17Y-serenity** [mx-2/gnome-shell-sass#1]
_Sorry, didn't know enter would paste this incomplete in GitHub._ 

Top bar, System Menu buttons, hard to differentiate between active and inactive.  

https://user-images.githubusercontent.com/100675600/197416649-997dd9c2-969d-4394-aaf8-3e6d7e44f4c8.mp4

**Comment by mx-2** [comment]
I added visible borders to that "checked" buttons. @53R3n17Y-serenity, can you please that https://github.com/mx-2/gnome-shell-sass/releases/tag/good-old-shell-43-testing fixes the issue?

**Comment by mx-2** [comment]
Fixed in release 43.1.
