### ISSUE TITLE
Text and icons go dark after applying a GDM picture.

### ISSUE THREAD

**Issue by in4matix** [mx-2/gnome-shell-sass#2]
As described above. Tried fixing by re-installing the shell theme, but issue is persistent.

**Comment by mx-2** [comment]
Can you please give more details about your system and the installation method, e.g.:

* Distribution, distribution version, good-old-shell version
* Was GDM installation permormed manually or via the `build_gresource` script, in the latter case:
   What were the arguments to the script?
* Does this only affect GDM or the whole desktop?
* Have you replaced the bundled background images?
